name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Adding host to known_hosts file..."
        ssh-keyscan -H "ec2-18-117-18-96.us-east-2.compute.amazonaws.com" >> ~/.ssh/known_hosts
        echo "Verifying SSH key with ssh-keygen:"
        ssh-keygen -lf ~/.ssh/id_rsa

    - name: Test SSH Connection
      env:
        EC2_USER: ubuntu
        EC2_HOST: ec2-18-117-18-96.us-east-2.compute.amazonaws.com
      run: |
        echo "Testing SSH connection..."
        ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "echo 'SSH connection successful'"

    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu
        EC2_HOST: ec2-18-117-18-96.us-east-2.compute.amazonaws.com
      run: |
        ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
          echo "Navigating to project directory..."
          cd AI_Education || exit 1  # Ensure the directory exists or exit
          
          echo "Pulling latest code..."
          git pull origin main
          
          echo "Activating virtual environment..."
          source venv/bin/activate
          
          echo "Installing dependencies..."
          pip install -r requirements.txt
          
          echo "Applying migrations and collecting static files..."
          python manage.py migrate
          python manage.py collectstatic --noinput
          
          echo "Restarting Gunicorn service..."
          sudo systemctl restart gunicorn  # Ensure ubuntu user has sudo privileges
        EOF
